### ISSUE TITLE
Привет, не могу запустить проект, как исправить ошибку?

### ISSUE THREAD

**Issue by nazirjonmakhmadkulov** [fajarca/android-clean-architecture-coroutine#2]
![image](https://user-images.githubusercontent.com/38754200/131626522-8310cc6f-d6c5-4dd2-aeee-551baa6c3b28.png)

**Comment by anddever** [comment]
@nazirjonmakhmadkulov Привет, как ты решил данную ошибку?

**Comment by nazirjonmakhmadkulov** [comment]
> @nazirjonmakhmadkulov Привет, как ты решил данную ошибку?
не решил
